### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by OlisCode** [Feserich/mib2std-zr-firmware-upgrade#1]
Just wanted to point out that aparrently not all SD readers seem to support the mentioned operration with only one data line.
I have tried out 4 usb ones and one notebook internal one and only one was working (old one from csl that I can't find anywhere online anymore)
the other ones were giving strange output in dmesg or just did not read/write.
Also it seems to be necessary to connect both vdd lines.
As a last note with my unit it was very hard (almost impossible) to solder to the vias (oxidation, huge copper planes pulling away the heat).
Maybe you wanna add these information to the readme.

**Comment by Feserich** [comment]
Hello,
nice to see, that my how-to is used also by someone else :)

Reading out the data was also quite hard for me. I applied the probes multiple times in different angles, removed oxidation with a scalpel and pushed the probes with the very sharp tip sensitive into the contact surface. 
From that experience it's really hard to tell, if the root cause of your observations were actually coming from a lose contact. 

The SD card reader I used is from "Hama" with a clear case and model number 00091092. You can still buy it online. 
The next weeks I will add some further information to the documentation. 

At the end was it working for you? Were you able also to apply the firmware upgrade?

**Comment by OlisCode** [comment]
I am 99% sure that my problems were not coming from bad contact, I soldered some very thin wires to the contact points and on the other side to an micro sd to standard sd card adapter.
This way I was able to quickly switch the reader and verify that my problems (except the mentioned need to connect both vdd lines) were caused by the reader not understanding that it should only use 1 data line.
I also further verified this by using a normal sd card and taping over the other data lines (only the one of my readers worked).
Some of the ones that did not work were also giving output in dmesg that they are switching to bus width 3 which obviously can't work in this case.
If anyone wants to replicate my method it is important to glue the little lock switch in place in order to be able to write to the chip.
At the end I was able to read and write the chip using your scripts however I did all of this not to update the firmware but instead install the toolbox from https://github.com/olli991/mib-std2-pq-zr-toolbox

I also wanted to give a huge thank you for sharing all the information publicly, free of charge and in such a great way.

**Comment by Feserich** [comment]
Thank you for the clarification. I updated the documentation. 
I also planed to install the toolbox, but till now the desire to have it was not outweighing the risk to damage something. 
My origin motivation for this procedure was to get Android Auto running stable. Before that my Headunit crashed frequently, which was resolved by this update. 

You're welcome! This was also my motivation. The documentations I found were just documenting some of the intermediate steps or very bad described. Some people have the knowledge, but they don't want to share it. Just offering to send them the ECU and do it for you. 
So I'm always glad to help.
